POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Maria da Silva",
    "email": "maria@upf.br"
}

###
GET http://localhost:3000/api/users

###
PUT http://localhost:3000/api/users/3
Content-Type: application/json

{
    "name": "Maria da Silva",
    "email": "maria@upf.br"
}

###
DELETE http://localhost:3000/api/users/3